### ISSUE TITLE
[Question] Why intermittently cannot find SpoolDir?

### ISSUE THREAD

**Issue by scheung38** [confluentinc/demo-scene#140]
After cloning project and docker-compose up initially fine:

with data/unprocessed/sample.csv

```
Isabella,42567,Girl
Sophia,42261,Girl
Jacob,42164,Boy
Emma,35951,Girl
Ethan,34523,Boy
Mason,34195,Boy
William,34130,Boy
Olivia,34128,Girl
Jayden,33962,Boy
Ava,30765,Girl
```

docker-compose ps
```
     Name                    Command                       State                        Ports              
-----------------------------------------------------------------------------------------------------------
kafka             /etc/confluent/docker/run        Up                      0.0.0.0:9092->9092/tcp          
kafka-connect     bash -c echo "Installing c ...   Up (health: starting)   0.0.0.0:8083->8083/tcp, 9092/tcp
kafkacat          /bin/sh -c apk add jq;           Up                                                      
                  wh ...                                                                                   
ksqldb            /usr/bin/docker/run              Up                      0.0.0.0:8088->8088/tcp          
postgres          docker-entrypoint.sh postgres    Up                      5432/tcp                        
schema-registry   /etc/confluent/docker/run        Up                      0.0.0.0:8081->8081/tcp          
zookeeper         /etc/confluent/docker/run        Up                      2181/tcp, 2888/tcp, 3888/tcp 
```

```
curl -s localhost:8083/connector-plugins|jq '.[].class'|egrep 'SpoolDir'

"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirLineDelimitedSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSchemaLessJsonSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.elf.SpoolDirELFSourceConnector"
```

Create the connector as per doc:

```
curl -i -X PUT -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/source-csv-spooldir-00/config \
    -d '{
        "connector.class": "com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector",
        "topic": "orders_spooldir_00",
        "input.path": "/data/unprocessed",
        "finished.path": "/data/processed",
        "error.path": "/data/error",
        "input.file.pattern": ".*\\.csv",
        "schema.generation.enabled":"true",
        "csv.first.row.as.header":"true"
        }'
```

Then sometime later:

docker-compose ps
```

     Name                    Command                       State                        Ports              
-----------------------------------------------------------------------------------------------------------
kafka             /etc/confluent/docker/run        Exit 1                                                  
kafka-connect     bash -c echo "Installing c ...   Up (health: starting)   0.0.0.0:8083->8083/tcp, 9092/tcp
kafkacat          /bin/sh -c apk add jq;           Up                                                      
                  wh ...                                                                                   
ksqldb            /usr/bin/docker/run              Exit 255                                                
postgres          docker-entrypoint.sh postgres    Up                      5432/tcp                        
schema-registry   /etc/confluent/docker/run        Exit 1                                                  
zookeeper         /etc/confluent/docker/run        Up                      2181/tcp, 2888/tcp, 3888/tcp
```

Some log:

```
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1596284656874) timed out at 1596284656875 after 1 attempt(s)
schema-registry    | Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
schema-registry    | [main] INFO io.confluent.admin.utils.ClusterStatus - Expected 1 brokers but found only 0. Trying to query Kafka for metadata again ...
schema-registry    | [main] ERROR io.confluent.admin.utils.ClusterStatus - Expected 1 brokers but found only 0. Brokers found [].
schema-registry exited with code 1
ksqldb             | [2020-08-01 12:24:38,879] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:60)
ksqldb             | io.confluent.ksql.util.KsqlServerException: Could not get Kafka cluster configuration!
ksqldb             | 	at io.confluent.ksql.services.KafkaClusterUtil.getConfig(KafkaClusterUtil.java:90)
ksqldb             | 	at io.confluent.ksql.security.KsqlAuthorizationValidatorFactory.isKafkaAuthorizerEnabled(KsqlAuthorizationValidatorFactory.java:81)
ksqldb             | 	at io.confluent.ksql.security.KsqlAuthorizationValidatorFactory.create(KsqlAuthorizationValidatorFactory.java:51)
ksqldb             | 	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:624)
ksqldb             | 	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:544)
ksqldb             | 	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:98)
ksqldb             | 	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:56)
ksqldb             | Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1596284678874) timed out at 1596284678875 after 1 attempt(s)
ksqldb             | 	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
ksqldb             | 	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
ksqldb             | 	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
ksqldb             | 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
ksqldb             | 	at io.confluent.ksql.services.KafkaClusterUtil.getConfig(KafkaClusterUtil.java:60)
ksqldb             | 	... 6 more
ksqldb             | Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1596284678874) timed out at 1596284678875 after 1 attempt(s)
ksqldb             | Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
ksqldb exited with code 255
```

and 

curl -s localhost:8083/connector-plugins|jq '.[].class'|egrep 'SpoolDir'

Does not return anything? 

and needing to restart docker-compose up again before 

curl -s localhost:8083/connector-plugins|jq '.[].class'|egrep 'SpoolDir'

to return the expected:

"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceConnector"

EDIT:

Seems to work now, as before there was no schema, now everytime a new csv with schema is placed into the unprocessed directory it is ingested, but would like to know how NOT to reingest an already processed csv file?

Say I dragged sample.csv from processed back to unprocessed directory, it should or not reprocess again? Do I have option not to reprocess again if csv file is already in processed directory? 

EDIT:

But if testing for another csv file of the same name that is already in processed directory by issuing another

```
curl -i -X PUT -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/source-csv-spooldir-00/config \
    -d '{
        "connector.class": "com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector",
        "topic": "orders_spooldir_00",
        "input.path": "/data/unprocessed",
        "finished.path": "/data/processed",
        "error.path": "/data/error",
        "input.file.pattern": ".*\\.csv",
        "schema.generation.enabled":"true",
        "csv.first.row.as.header":"true"
        }'
``` 

curl: (52) Empty reply from server

Can these questions be more easily answered from ksqlDB?

How many different boys' names are there that begin with the letter Z? (Count the names, not the people.)
What is the most common girl's name that begins with the letter Q?

docker --version
Docker version 19.03.12, build 48a66213fe

Mac OSX Catalina 10.15.6

**Comment by rmoff** [comment]
How much memory have you allocated to Docker? What's the `docker-compose logs kafka` show as the reason for it exiting? 

For general questions about the capabilities of ksqlDB head to http://cnfl.io/slack and the #ksqldb channel.

**Comment by scheung38** [comment]
<img width="1201" alt="Screenshot 2020-08-09 at 22 24 11" src="https://user-images.githubusercontent.com/1273014/89742128-13778580-da8f-11ea-8e0f-c3daf0a0d2f5.png">

Hi Robin

Is confluent-hub install jcustenborder/kafka-connect-spooldir:2.0.43 a one time install?

Not sure why this is needed every time Mac machine starts up

curl -s localhost:8083/connector-plugins|jq '.[].class'|egrep 'SpoolDir

does not return anything until installation of this connector happens next time?

**Comment by scheung38** [comment]
OK 

now it is returning:

<img width="880" alt="Screenshot 2020-08-09 at 22 27 17" src="https://user-images.githubusercontent.com/1273014/89742172-8123b180-da8f-11ea-906c-cb7a683294c2.png">
