### ISSUE TITLE
{"error_code":500,"message":null} on creating a new connector

### ISSUE THREAD

**Issue by KamilaLis** [confluentinc/demo-scene#158]
Hi! 
I'm using `kafka-connect-zero-to-hero/docker-compose.yml`. I changed it by adding `confluentinc/kafka-connect-ftps:1.0.2-preview` [here](https://github.com/confluentinc/demo-scene/blob/master/kafka-connect-zero-to-hero/docker-compose.yml#L111) and ftp server
```
  vsftpd:
    image: "fauria/vsftpd:latest"
    container_name: vsftpd
    ports:
      - 21:21
      - 20:20
    environment:
      FTP_USER: "name"
      FTP_PASS: "pass"
    volumes:
      - ${PWD}/data:/data
``` 

When I'm sending
 ```
    curl -i -X PUT -H  "Content-Type:application/json" \
    http://localhost:8083/connectors/source-ftps/config \
    -d '{
            "connector.class": "io.confluent.connect.ftps.FtpsSourceConnector",
            "kafka.topic": "default.demo" ,
            "confluent.topic.bootstrap.servers": "kafka:29092",
            "ftps.host": "vsftpd",
            "ftps.username": "name",
            "ftps.password": "pass",
            "ftps.input.path": "/data"
    }'
 ```
to start connector I'm getting an error `{"error_code":500,"message":null}`. 

Kafka-connect logs: 

```
kafka-connect      | [2020-09-30 10:33:08,446] ERROR Uncaught exception in REST call to /connectors/FTPSConnector/config (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper:61)
kafka-connect      | java.lang.NullPointerException
kafka-connect      |    at java.io.File.<init>(File.java:277)
kafka-connect      |    at io.confluent.connect.ftps.connection.FtpsConnection.createSslContext(FtpsConnection.java:132)
kafka-connect      |    at io.confluent.connect.ftps.connection.FtpsConnection.<init>(FtpsConnection.java:45)
kafka-connect      |    at io.confluent.connect.ftps.source.validation.FtpsSourceConfigValidation.performValidation(FtpsSourceConfigValidation.java:52)
kafka-connect      |    at io.confluent.connect.utils.validators.all.ConfigValidation.validate(ConfigValidation.java:185)
kafka-connect      |    at io.confluent.connect.ftps.FtpsSourceConnector.validate(FtpsSourceConnector.java:80)
kafka-connect      |    at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:313)
kafka-connect      |    at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:745)
kafka-connect      |    at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:742)
kafka-connect      |    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:342)
kafka-connect      |    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:282)
kafka-connect      |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
kafka-connect      |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
kafka-connect      |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
kafka-connect      |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
kafka-connect      |    at java.lang.Thread.run(Thread.java:748)
```

Do you have any idea what can be wrong?
Thank you in advance!

**Comment by rmoff** [comment]
Hi, the best place to ask this is on:
→ Slack group: http://cnfl.io/slack
or
→ Mailing list: https://groups.google.com/forum/#!forum/confluent-platform

You might also find this useful from @vdesabou: https://github.com/vdesabou/kafka-docker-playground/tree/master/connect/connect-ftps-source

thanks!
