### ISSUE TITLE
Not able to retrieve proper JSON

### ISSUE THREAD

**Issue by coolboi567** [confluentinc/demo-scene#54]
I have a large MongoDump JSON which I need to put it in Kafka using Kafka Connect.

Using the configuration present in [source-data-users-json-noschema.json](https://github.com/confluentinc/demo-scene/blob/master/connect-deepdive/config/source-data-users-json-noschema.json), I am not able to obtain proper JSON. The keys are null (which is fine) but, the values get treated as a string and enclosed within double quotes while escaping the quotes present within.

I was able to get the proper-lookalike JSON while treating the value as `org.apache.kafka.connect.storage.StringConverter`. 

Eitherway, I am only able to digest 15k-30k data which is not even 10% of the total data. It says the following before it stops ingesting.
```
[2019-03-15 08:48:13,812] ERROR WorkerSourceTask{id=orderdata-test18-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
java.lang.NegativeArraySizeException
        at org.apache.kafka.connect.file.FileStreamSourceTask.poll(FileStreamSourceTask.java:141)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-03-15 08:48:13,814] ERROR WorkerSourceTask{id=orderdata-test18-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
```

**Comment by sknop** [comment]
This is rather surprising

the line in question is this

 char[] newbuf = new char[buffer.length * 2];

buffer is initialised here (line 51)

private char[] buffer = new char[1024];
// ...

so if this exception is correct, buffer.length must be negative, and I cannot quite see how that can happen.

**Comment by rmoff** [comment]
If the data is JSON already then `org.apache.kafka.connect.storage.StringConverter` is probably the correct converter to use for `value.converter`. 

Either way, I don't think this has anything to do with the repo here, so closing this issue. 

For general questions, the best place to ask this is on: 
* Mailing list: https://groups.google.com/forum/#!forum/confluent-platform
* Slack group: https://slackpass.io/confluentcommunity
