### ISSUE TITLE
[rail-data-streaming-pipeline] - Kafka shutting down

### ISSUE THREAD

**Issue by derplarsen** [confluentinc/demo-scene#80]
When I run docker-compose, everything shows UP -  but when running the ingest_00.sh script I'm getting an error saying no reply from server.. 

When i look at the docker-compose logs i'm seeing issues connecting kibana to elasticsearch, but i think it's a red herring -

```
kibana              | {"type":"log","@timestamp":"2019-08-27T02:58:56Z","tags":["license","warning","xpack"],"pid":1,"message":"License information from the X-Pack plugin could not be obtained from Elasticsearch for the [data] cluster. Error: No Living connections"}
kibana              | {"type":"log","@timestamp":"2019-08-27T02:58:56Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana              | {"type":"log","@timestamp":"2019-08-27T02:58:56Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
```

Elasticsearch doesn't appear to throw any errors. BUT Kafka shut down, error here:

```
kafka               | [2019-08-27 02:55:36,553] INFO Socket connection established to zookeeper/172.20.0.6:2181, initiating session (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:55:36,571] INFO Session establishment complete on server zookeeper/172.20.0.6:2181, sessionid = 0x1000263ea780001, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:55:36,642] INFO [ZooKeeperClient] Connected. (kafka.zookeeper.ZooKeeperClient)
kafka               | [2019-08-27 02:55:53,640] INFO Unable to read additional data from server sessionid 0x1000263ea780001, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:04,403] INFO Opening socket connection to server zookeeper/172.20.0.6:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:04,923] INFO Socket connection established to zookeeper/172.20.0.6:2181, initiating session (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:06,751] WARN Unable to reconnect to ZooKeeper service, session 0x1000263ea780001 has expired (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:06,963] INFO Unable to reconnect to ZooKeeper service, session 0x1000263ea780001 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:12,991] INFO [ZooKeeperClient] Session expired. (kafka.zookeeper.ZooKeeperClient)
kafka               | [2019-08-27 02:56:13,021] INFO EventThread shut down for session: 0x1000263ea780001 (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:14,472] INFO [ZooKeeperClient] Initializing a new session to zookeeper:2181. (kafka.zookeeper.ZooKeeperClient)
kafka               | [2019-08-27 02:56:14,818] INFO Initiating client connection, connectString=zookeeper:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@3c9754d8 (org.apache.zookeeper.ZooKeeper)
kafka               | [2019-08-27 02:56:16,911] INFO Opening socket connection to server zookeeper/172.20.0.6:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:16,936] INFO Socket connection established to zookeeper/172.20.0.6:2181, initiating session (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:17,169] INFO Session establishment complete on server zookeeper/172.20.0.6:2181, sessionid = 0x1000263ea780002, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:18,488] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka               | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /consumers
kafka               | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:130)
kafka               | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
kafka               | 	at kafka.zookeeper.AsyncResponse.maybeThrow(ZooKeeperClient.scala:544)
kafka               | 	at kafka.zk.KafkaZkClient.createRecursive(KafkaZkClient.scala:1610)
kafka               | 	at kafka.zk.KafkaZkClient.makeSurePersistentPathExists(KafkaZkClient.scala:1532)
kafka               | 	at kafka.zk.KafkaZkClient$$anonfun$createTopLevelPaths$1.apply(KafkaZkClient.scala:1524)
kafka               | 	at kafka.zk.KafkaZkClient$$anonfun$createTopLevelPaths$1.apply(KafkaZkClient.scala:1524)
kafka               | 	at scala.collection.immutable.List.foreach(List.scala:392)
kafka               | 	at kafka.zk.KafkaZkClient.createTopLevelPaths(KafkaZkClient.scala:1524)
kafka               | 	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:386)
kafka               | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:205)
kafka               | 	at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:114)
kafka               | 	at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)
kafka               | [2019-08-27 02:56:18,579] INFO shutting down (kafka.server.KafkaServer)
kafka               | [2019-08-27 02:56:18,692] INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient)
kafka               | [2019-08-27 02:56:18,791] INFO EventThread shut down for session: 0x1000263ea780002 (org.apache.zookeeper.ClientCnxn)
kafka               | [2019-08-27 02:56:18,794] INFO Session: 0x1000263ea780002 closed (org.apache.zookeeper.ZooKeeper)
kafka               | [2019-08-27 02:56:18,802] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
kafka               | [2019-08-27 02:56:18,876] INFO shut down completed (kafka.server.KafkaServer)
kafka               | [2019-08-27 02:56:18,888] INFO Shutting down SupportedServerStartable (io.confluent.support.metrics.SupportedServerStartable)
kafka               | [2019-08-27 02:56:18,888] INFO Closing BaseMetricsReporter (io.confluent.support.metrics.BaseMetricsReporter)
kafka               | [2019-08-27 02:56:18,889] INFO Waiting for metrics thread to exit (io.confluent.support.metrics.SupportedServerStartable)
kafka               | [2019-08-27 02:56:18,889] INFO Shutting down KafkaServer (io.confluent.support.metrics.SupportedServerStartable)
kafka               | [2019-08-27 02:56:18,892] INFO shutting down (kafka.server.KafkaServer)
```

**In the early part of the logs I see it can't resolve kafka:29092..** : 

```
[main] WARN org.apache.kafka.clients.ClientUtils - Couldn't resolve server kafka:29092 from bootstrap.servers as DNS resolution failed for kafka
kafka-connect-02    | [main] ERROR io.confluent.admin.utils.cli.KafkaReadyCommand - Error while running kafka-ready.
kafka-connect-02    | org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
kafka-connect-02    | 	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:386)
kafka-connect-02    | 	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:65)
kafka-connect-02    | 	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:138)
kafka-connect-02    | 	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150)
kafka-connect-02    | Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
kafka-connect-02    | 	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:90)
kafka-connect-02    | 	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:49)
kafka-connect-02    | 	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:346)
kafka-connect-02    | 	... 3 more
```

**When i run this first curl post in the 00_ingest.sh file ..**

```
curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:8083/connectors/ -d '{
  "name": "source-activemq-networkrail-TRAIN_MVT_EA_TOC-01",
  "config": {
    "connector.class": "io.confluent.connect.activemq.ActiveMQSourceConnector",
    "activemq.url": "tcp://datafeeds.networkrail.co.uk:61619",
    "activemq.username": "${file:/data/credentials.properties:NROD_USERNAME}",
    "activemq.password": "${file:/data/credentials.properties:NROD_PASSWORD}",
    "jms.destination.type": "topic",
    "jms.destination.name": "TRAIN_MVT_EA_TOC",
    "kafka.topic": "networkrail_TRAIN_MVT",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schemas.enable": "false",
    "confluent.license": "",
    "confluent.topic.bootstrap.servers": "kafka:29092",
    "confluent.topic.replication.factor": 1
  }
}'
```

This is the response:
`curl: (52) Empty reply from server`

Would love some insight on this :pray:

**Comment by rmoff** [comment]
@derplarsen which demo are you running? Is this the rail one?

**Comment by rmoff** [comment]
@derplarsen Have you allocated >=8GB of memory to Docker on your machine? It looks like several components have failed to start up. 

If you have, then the next step would be to bring everything up (`docker-compose up -d`) and then once things are running copy the output of `docker-compose ps` and paste it here.

**Comment by chrislarsenqlik** [comment]
Thanks Robin, I did allocate at least 8GB RAM but I'm having other issues with docker on my laptop as well. I did 2 resets with mixed results, I'm trying to find out how to do a more sanifying (?) reset and will respond back here whether that fixed it.

**Comment by rmoff** [comment]
@derplarsen a nuclear option is `docker system prune -af`. This will blitz everything.
